--Dimension_Tables
CREATE TABLE Dim_Product (
    product_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR2(100) NOT NULL,
    category     VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_product_category CHECK (category IN ('alcoholic', 'non-alcoholic'))
);
CREATE TABLE Dim_Time (
    time_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calendar_date DATE NOT NULL,
    day_of_month  NUMBER(2) NOT NULL,
    week_of_year  NUMBER(2) NOT NULL,
    month_number  NUMBER(2) NOT NULL,
    quarter       NUMBER(1) NOT NULL,
    year_number   NUMBER(4) NOT NULL,
    CONSTRAINT uq_time_date UNIQUE (calendar_date),
    CONSTRAINT chk_quarter CHECK (quarter BETWEEN 1 AND 4)
);
CREATE TABLE Dim_Branch (
    branch_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_name VARCHAR2(50) NOT NULL,
    region      VARCHAR2(10) NOT NULL,
    CONSTRAINT chk_branch_region CHECK (region IN ('east', 'west', 'north', 'south'))
);
CREATE TABLE Dim_Customer (
    customer_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR2(50) NOT NULL,
    last_name     VARCHAR2(50) NOT NULL,
    street        VARCHAR2(100) NOT NULL,
    house_number  VARCHAR2(10) NOT NULL,
    zip_code      VARCHAR2(15) NOT NULL,
    city          VARCHAR2(50) NOT NULL,
    gender        CHAR(1) NOT NULL,
    date_of_birth DATE NOT NULL,
    age_group     VARCHAR2(20) NOT NULL,
    CONSTRAINT chk_customer_gender CHECK (gender IN ('M', 'F', 'D', 'O')), -- Male, Female, Diverse, Other
    CONSTRAINT chk_customer_age_group CHECK (age_group IN ('child', 'youngster', 'young adult', 'adult', 'old adult'))
);

-- Facts
CREATE TABLE Fact_Sales (
    product_id      NUMBER NOT NULL,
    time_id         NUMBER NOT NULL,
    branch_id       NUMBER NOT NULL,
    customer_id     NUMBER NOT NULL,
    quantity_liters NUMBER(10, 2) NOT NULL,
    --Constaints,foreign keys and primary key(composite key)
    CONSTRAINT pk_fact_sales PRIMARY KEY (product_id, time_id, branch_id, customer_id),
    CONSTRAINT fk_sales_product FOREIGN KEY (product_id) REFERENCES Dim_Product(product_id),
    CONSTRAINT fk_sales_time FOREIGN KEY (time_id) REFERENCES Dim_Time(time_id),
    CONSTRAINT fk_sales_branch FOREIGN KEY (branch_id) REFERENCES Dim_Branch(branch_id),
    CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id) REFERENCES Dim_Customer(customer_id),
    
    CONSTRAINT chk_positive_quantity CHECK (quantity_liters > 0)
);